-- Lodestar Guides: Horde 30-35: Desolace
--
-- GENERATED by tools/router/generate_route.lua from the merged database (Vanilla + ATT + the
-- beta harvest). Regenerate rather than hand-editing, or the next harvest will overwrite you.
-- --regen-args: 405 --name "Horde 30-35: Desolace" --faction "Horde" --levels "30-35" --next "Horde 35-40: Stranglethorn Vale" --zone "Desolace" --max-level "37" --min-level "27"
--
-- 31 quests on uiMapID 405 had a known giver position; 15 carried a prerequisite chain, which is
-- what fixes the order. Quests the data cannot place yet are not in here at all -- smart mode
-- covers those, and they appear as soon as someone walks past their giver.
local Guide = _G.Lodestar:GetModule("Guide")

Guide:RegisterGuide([[
#guide Horde 30-35: Desolace
#faction Horde
#levels 30-35
#next Horde 35-40: Stranglethorn Vale
#author Lodestar (generated)
#note Generated from harvested and ATT data. Order follows the quest chains; positions are where players actually found things.

step
  .optional >>Needs Alliance Relations, which starts in Orgrimmar
  .goto Desolace,52.6,54.4
  .accept 1434 >>Accept Befouled by Satyr (lvl 25) from Takata Steelblade

step
  .optional >>Needs Alliance Relations, which starts in Orgrimmar
  .goto Desolace,52.6,54.4
  .accept 1433 >>Accept Alliance Relations (lvl 30) from Takata Steelblade

step
  .optional >>Needs The Kolkar of Desolace, which starts in The Barrens
  .goto Desolace,56.2,59.6
  .accept 1365 >>Accept Khan Dez'hepah (lvl 30) from Felgur Twocuts

step
  .goto Desolace,56.3,59.7
  .accept 1368 >>Accept Gelkis Alliance (lvl 30) from Gurda Wildmane
  .accept 1367 >>Accept Magram Alliance (lvl 30) from Gurda Wildmane

step
  .goto Desolace,60.9,61.9
  .accept 5561 >>Accept Kodo Roundup (lvl 30) from Smeed Scrabblescrew

step
  .optional >>Needs The Kolkar of Desolace, which starts in The Barrens
  .goto Desolace,73.4,41.6
  .complete 1365 >>Finish Khan Dez'hepah

step
  .optional >>Needs Alliance Relations, which starts in Orgrimmar
  .goto Desolace,75.3,19.3
  .complete 1434 >>Finish Befouled by Satyr

step
  .complete 5561 >>Finish Kodo Roundup

step
  .optional >>Needs Alliance Relations, which starts in Orgrimmar
  .goto Desolace,52.2,53.4
  .turnin 1433 >>Turn in Alliance Relations to Maurin Bonesplitter

step
  .optional >>Needs Alliance Relations, which starts in Orgrimmar
  .goto Desolace,52.6,54.4
  .turnin 1434 >>Turn in Befouled by Satyr to Takata Steelblade

step
  .optional >>Needs The Kolkar of Desolace, which starts in The Barrens
  .goto Desolace,56.2,59.6
  .turnin 1365 >>Turn in Khan Dez'hepah to Felgur Twocuts

step
  .goto Desolace,60.9,61.9
  .turnin 5561 >>Turn in Kodo Roundup to Smeed Scrabblescrew

step
  .goto Desolace,75.0,68.2
  .turnin 1367 >>Turn in Magram Alliance to Warug

step
  .goto Desolace,36.2,79.2
  .turnin 1368 >>Turn in Gelkis Alliance to Uthek the Wise
  .accept 1370 >>Accept Stealing Supplies (lvl 30) from Uthek the Wise

step
  .goto Desolace,39.5,78.1
  .accept 5821 >>Accept Bodyguard for Hire (lvl 30) from Cork Gizelton

step
  .goto Desolace,70.9,75.4
  .complete 1370 >>Finish Stealing Supplies

step
  .goto Desolace,60.9,61.9
  .turnin 5821 >>Turn in Bodyguard for Hire to Smeed Scrabblescrew

step
  .goto Desolace,36.2,79.2
  .turnin 1370 >>Turn in Stealing Supplies to Uthek the Wise

step
  .xp 31

step
  .goto Desolace,36.2,79.2
  .accept 1373 >>Accept Ongeku (lvl 30) from Uthek the Wise

step
  .complete 1373 >>Finish Ongeku

step
  .goto Desolace,36.2,79.2
  .turnin 1373 >>Turn in Ongeku to Uthek the Wise
  .accept 1374 >>Accept Khan Jehn (lvl 30) from Uthek the Wise

step
  .goto Desolace,65.9,80.4
  .complete 1374 >>Finish Khan Jehn

step
  .goto Desolace,36.2,79.2
  .turnin 1374 >>Turn in Khan Jehn to Uthek the Wise
  .accept 1380 >>Accept Khan Hratha (lvl 30) from Uthek the Wise

step
  .goto Desolace,30.8,55.7
  .complete 1380 >>Finish Khan Hratha

step
  .goto Desolace,36.2,79.2
  .turnin 1380 >>Turn in Khan Hratha to Uthek the Wise

step
  .goto Desolace,25.0,72.3
  .accept 5763 >>Accept Hunting in Stranglethorn (lvl 28) from Roon Wildmane

step
  .goto Desolace,22.6,72.0
  .accept 6142 >>Accept Clam Bait (lvl 31) from Mai'Lahii

step
  .goto Desolace,34.1,30.7
  .complete 6142 >>Finish Clam Bait

step
  .optional >>Handed in outside this zone, to Hemet Nesingwary
  .turnin 5763 >>Turn in Hunting in Stranglethorn to Hemet Nesingwary (not in this zone)

step
  .goto Desolace,22.6,72.0
  .turnin 6142 >>Turn in Clam Bait to Mai'Lahii

step
  .xp 32

step
  .goto Desolace,23.3,72.9
  .accept 6143 >>Accept Other Fish to Fry (lvl 32) from Drulzegar Skraghook

step
  .goto Desolace,25.8,68.2
  .accept 5381 >>Accept Hand of Iruxos (lvl 32) from Taiga Wisemane

step
  .goto Desolace,35.4,22.0
  .complete 6143 >>Finish Other Fish to Fry

step
  .complete 5381 >>Finish Hand of Iruxos

step
  .goto Desolace,25.8,68.2
  .turnin 5381 >>Turn in Hand of Iruxos to Taiga Wisemane

step
  .goto Desolace,23.3,72.9
  .turnin 6143 >>Turn in Other Fish to Fry to Drulzegar Skraghook

step
  .goto Desolace,25.8,68.2
  .accept 5581 >>Accept Portals of the Legion (lvl 32) from Taiga Wisemane

step
  .complete 5581 >>Finish Portals of the Legion

step
  .goto Desolace,25.8,68.2
  .turnin 5581 >>Turn in Portals of the Legion to Taiga Wisemane

step
  .goto Desolace,52.6,54.4
  .accept 1436 >>Accept Alliance Relations (lvl 30) from Takata Steelblade

step
  .goto Desolace,55.4,55.8
  .accept 5386 >>Accept Catch of the Day (lvl 32) from Nataka Longhorn

step
  .goto Desolace,56.2,59.6
  .accept 1366 >>Accept Centaur Bounty (lvl 30) from Felgur Twocuts

step
  .goto Desolace,70.1,45.7
  .complete 1366 >>Finish Centaur Bounty

step
  .complete 5386 >>Finish Catch of the Day

step
  .goto Desolace,55.4,55.8
  .turnin 5386 >>Turn in Catch of the Day to Nataka Longhorn

step
  .optional >>Handed in outside this zone, to Keldran
  .turnin 1436 >>Turn in Alliance Relations to Keldran (not in this zone)

step
  .goto Desolace,56.2,59.6
  .turnin 1366 >>Turn in Centaur Bounty to Felgur Twocuts

step
  .xp 33

step
  .goto Desolace,75.0,68.2
  .accept 1369 >>Accept Broken Tears (lvl 30) from Warug

step
  .goto Desolace,39.7,93.3
  .complete 1369 >>Finish Broken Tears

step
  .goto Desolace,75.0,68.2
  .turnin 1369 >>Turn in Broken Tears to Warug
  .accept 1371 >>Accept Gizmo for Warug (lvl 30) from Warug

step
  .complete 1371 >>Finish Gizmo for Warug

step
  .goto Desolace,75.0,68.2
  .turnin 1371 >>Turn in Gizmo for Warug to Warug
  .accept 1375 >>Accept Khan Shaka (lvl 30) from Warug

step
  .goto Desolace,40.5,95.5
  .complete 1375 >>Finish Khan Shaka

step
  .goto Desolace,75.0,68.2
  .turnin 1375 >>Turn in Khan Shaka to Warug
  .accept 1381 >>Accept Khan Hratha (lvl 30) from Warug

step
  .goto Desolace,30.8,55.7
  .complete 1381 >>Finish Khan Hratha

step
  .goto Desolace,75.0,68.2
  .turnin 1381 >>Turn in Khan Hratha to Warug

step
  .class Shaman
  .goto Desolace,88.5,48.2
  .accept 1532 >>Accept Call of Air (lvl 30) from Xanis Flameweaver

step
  .class Mage
  .goto Desolace,88.6,46.7
  .accept 1947 >>Accept Journey to the Marsh (lvl 30) from Ursyn Ghull

step
  .optional >>Handed in outside this zone, to Tabetha
  .class Mage
  .turnin 1947 >>Turn in Journey to the Marsh to Tabetha (not in this zone)

step
  .optional >>Handed in outside this zone, to Prate Cloudseer
  .class Shaman
  .turnin 1532 >>Turn in Call of Air to Prate Cloudseer (not in this zone)

step
  .xp 34

step
  .goto Desolace,62.3,39.0
  .accept 5501 >>Accept Bone Collector (lvl 33) from Bibbly F'utzbuckle

step
  .goto Desolace,51.1,60.0
  .complete 5501 >>Finish Bone Collector

step
  .goto Desolace,62.3,39.0
  .turnin 5501 >>Turn in Bone Collector to Bibbly F'utzbuckle

step
  .goto Desolace,38.9,27.2
  .accept 5741 >>Accept Sceptre of Light (lvl 30) from Azore Aldamort

step
  .goto Desolace,55.2,30.2
  .complete 5741 >>Finish Sceptre of Light

step
  .goto Desolace,38.9,27.2
  .turnin 5741 >>Turn in Sceptre of Light to Azore Aldamort
  .accept 6027 >>Accept Book of the Ancients (lvl 30) from Azore Aldamort

step
  .complete 6027 >>Finish Book of the Ancients

step
  .goto Desolace,38.9,27.2
  .turnin 6027 >>Turn in Book of the Ancients to Azore Aldamort

step
  .goto Desolace,33.9,53.5
  .accept 6132 >>Accept Get Me Out of Here! (lvl 34) from Melizza Brimbuzzle

step
  .goto Desolace,47.8,61.8
  .turnin 6132 >>Turn in Get Me Out of Here! to Hornizz Brimbuzzle
  .accept 6134 >>Accept Ghost-o-plasm Round Up (lvl 34) from Hornizz Brimbuzzle

step
  .goto Desolace,64.0,90.0
  .complete 6134 >>Finish Ghost-o-plasm Round Up

step
  .goto Desolace,47.8,61.8
  .turnin 6134 >>Turn in Ghost-o-plasm Round Up to Hornizz Brimbuzzle

step
  .xp 35 >>You should be 35 by now. If you are not, the rest of this zone will not be offered to you yet -- finish the optional quests above, or kill your way up, before carrying on.

step
  .class Mage
  .goto Desolace,88.6,46.7
  .accept 1953 >>Accept Return to the Marsh (lvl 35) from Ursyn Ghull

step
  .optional >>Handed in outside this zone, to Tabetha
  .class Mage
  .turnin 1953 >>Turn in Return to the Marsh to Tabetha (not in this zone)

]], "generated")
