#!/usr/bin/env python3
"""Generate tools/router/map_frames.py from the client's UiMap and UiMapAssignment tables.

    tools/wowdb/fetch.sh && python3 tools/wowdb/import_maps.py

A map frame is the rectangle that turns a map percentage into yards, and every travel time the
router computes depends on it. They were hand-entered from Astrolabe-era numbers for a 1.12 client,
which is a reconstruction of a different game than the one we route on. This reads the answer out of
the Forever beta client instead.

The two are almost identical, which is the point: 44 of 46 shared zones agree to within a yard, so
the hand table was good and this is not a rewrite for its own sake. It is the two that disagree, and
the ones that were never in it at all, that matter -- Mulgore is 20% larger than the hand table
says, and Forever's new zones (Zephras Isle, Riverglades, Shen'dralas, Darkspear Islands) were
simply absent.

Keys are a mess for a reason that predates this file. pfQuest coordinates carry an old area id and
the harvest's carry a uiMapID, and both end up in the same `c[0]` slot after Data.lua merges them.
So a frame is emitted under BOTH ids when a map has both, and a collision between the two numbering
systems is reported rather than silently resolved.
"""
from __future__ import annotations

import csv
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
SRC = os.path.join(HERE, "src")
OUT = os.path.join(ROOT, "tools", "router", "map_frames.py")


def rows(name):
    path = os.path.join(SRC, name + ".csv")
    if not os.path.exists(path):
        raise SystemExit(f"{path} missing; run tools/wowdb/fetch.sh first")
    return list(csv.DictReader(open(path, encoding="utf-8")))


def main() -> int:
    names = {int(r["ID"]): r.get("Name_lang", "") for r in rows("UiMap")}
    frames, by_area, collisions, skipped = {}, {}, [], 0
    for r in rows("UiMapAssignment"):
        ui, area, cont = int(r["UiMapID"]), int(r["AreaID"]), int(r["MapID"])
        # Region_0/3 span one world axis and Region_1/4 the other; 1/-1000000 is the unbounded
        # vertical extent and is not a rectangle edge.
        x0, y0 = float(r["Region_0"]), float(r["Region_1"])
        x1, y1 = float(r["Region_3"]), float(r["Region_4"])
        if not (abs(x1 - x0) > 1 and abs(y1 - y0) > 1):
            skipped += 1
            continue
        name = names.get(ui, "")
        # A uiMapID can be assigned more than once (a phased copy of a zone); the first wins, which
        # is the lower ID and therefore the original.
        if ui not in frames:
            frames[ui] = (name, cont, x0, y0, x1, y1)
        if area and area not in by_area:
            by_area[area] = ui

    for area in by_area:
        if area in frames and by_area[area] != area:
            collisions.append(area)

    lines = [
        '"""Map rectangles in yards, from the client\'s own UiMapAssignment table.',
        "",
        "GENERATED by tools/wowdb/import_maps.py. Do not edit -- rerun the importer.",
        "",
        "FRAMES is keyed by uiMapID. AREA_TO_UIMAP maps the old area id a pfQuest coordinate carries",
        "onto the uiMapID of the same place, because both numbering systems reach the router in the",
        "same slot once Data.lua has merged the sources.",
        '"""',
        "",
        "# uiMapID -> (name, continent, x0, y0, x1, y1)",
        "FRAMES: dict[int, tuple[str, int, float, float, float, float]] = {",
    ]
    for ui in sorted(frames):
        n, c, x0, y0, x1, y1 = frames[ui]
        lines.append(f'    {ui}: ({n!r}, {c}, {x0!r}, {y0!r}, {x1!r}, {y1!r}),')
    lines += ["}", "", "# old area id -> uiMapID", "AREA_TO_UIMAP: dict[int, int] = {"]
    for area in sorted(by_area):
        lines.append(f"    {area}: {by_area[area]},")
    lines += ["}", ""]
    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {len(frames)} frames, {len(by_area)} area ids"
          + (f", {skipped} assignments without a rectangle" if skipped else ""))
    if collisions:
        print("  WARNING: area id also used as a uiMapID:", collisions)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
