#!/usr/bin/env python3
"""Generate tools/router/taxi.py from the client's TaxiNodes / TaxiPath / TaxiPathNode tables.

    tools/wowdb/fetch.sh && python3 tools/wowdb/import_taxi.py

Every catalog the router has built so far reports "0 flights", so no planned route has ever taken
one: travel_options() only offers a flight between two nodes the player already knows, and nothing
ever filled catalog.flights. The hand-typed FLIGHT_MASTERS dict in vanilla_catalog.py has 28 names
and no edges at all, so even when a node was known the cost fell back to straight-line / TAXI_SPEED.

A flight path is not a straight line. TaxiPathNode holds the actual polyline the griffon flies, so
the length here is the length flown, and the ratio between the two is reported by the importer
(it is not small - see the summary line).

Node positions are in the same world-yard frame as UiMapAssignment's Region columns, which is what
map_frames.py already holds, so a node can be turned back into a (uiMapID, x%, y%) by whichever
frame contains it. That inversion lives in taxi_routes.py, not here; this file is data only.

Faction comes from Flags: bit 0 shows the node on the Alliance flight map, bit 1 on the Horde one.
The split it produces is exactly the Classic one (Stormwind/Ironforge/Auberdine vs Orgrimmar/
Undercity/Crossroads, with Booty Bay, Gadgetzan, Everlook and Moonglade appearing in both lists as
separate per-faction nodes), which is the check that the bits mean what they look like.

Excluded: `zzOLD` nodes (renamed/moved, kept in the table for save compatibility), `Quest Path`
scripted flights, and the `Transport` / `Generic` targets that drive boats and zeppelins. The last
of those is why cross-continent travel still costs infinity - a zeppelin is not a taxi node the
player can select.
"""
from __future__ import annotations

import collections
import csv
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
SRC = os.path.join(HERE, "src")
OUT = os.path.join(ROOT, "tools", "router", "taxi.py")

SKIP_PREFIX = ("zzOLD", "Quest Path", "Transport,", "Generic,", "Programmer Isle")


def rows(name):
    path = os.path.join(SRC, name + ".csv")
    if not os.path.exists(path):
        raise SystemExit(f"{path} missing; run tools/wowdb/fetch.sh first")
    return list(csv.DictReader(open(path, encoding="utf-8")))


def faction(flags: int) -> str:
    a, h = bool(flags & 1), bool(flags & 2)
    return "Both" if a and h else "Alliance" if a else "Horde" if h else ""


def main() -> int:
    nodes = {}
    for r in rows("TaxiNodes"):
        name = r["Name_lang"]
        if name.startswith(SKIP_PREFIX):
            continue
        nodes[int(r["ID"])] = (name, int(r["ContinentID"]), float(r["Pos_0"]), float(r["Pos_1"]),
                               faction(int(r["Flags"])))

    poly = collections.defaultdict(list)
    for r in rows("TaxiPathNode"):
        poly[int(r["PathID"])].append((int(r["NodeIndex"]), float(r["Loc_0"]), float(r["Loc_1"]), float(r["Loc_2"])))

    edges, straight, flown, dangling, noline = {}, 0.0, 0.0, 0, 0
    for r in rows("TaxiPath"):
        a, b = int(r["FromTaxiNode"]), int(r["ToTaxiNode"])
        if a not in nodes or b not in nodes:
            dangling += 1
            continue
        pts = [p[1:] for p in sorted(poly.get(int(r["ID"]), []))]
        if len(pts) < 2:
            noline += 1
            continue
        yards = sum(math.dist(pts[i], pts[i + 1]) for i in range(len(pts) - 1))
        # a node pair can have more than one path (a scenic one and a direct one); keep the shorter
        if edges.get((a, b), math.inf) > yards:
            edges[(a, b)] = yards
        straight += math.dist(nodes[a][2:4], nodes[b][2:4])
        flown += yards

    lines = [
        '"""Flight network from the client: node positions, factions, and flown path lengths.',
        "",
        "GENERATED by tools/wowdb/import_taxi.py. Do not edit -- rerun the importer.",
        "",
        "NODES  taxi node id -> (name, continent, world x, world y, faction)",
        "       faction is Alliance / Horde / Both / '' (not selectable on either flight map).",
        "EDGES  (from id, to id) -> yards actually flown along TaxiPathNode's polyline, which is",
        "       longer than the straight line between the two nodes. Directed: the return leg is a",
        "       separate path and is usually a slightly different length.",
        '"""',
        "",
        "NODES: dict[int, tuple[str, int, float, float, str]] = {",
    ]
    for i in sorted(nodes):
        n, c, x, y, f = nodes[i]
        lines.append(f"    {i}: ({n!r}, {c}, {x!r}, {y!r}, {f!r}),")
    lines += ["}", "", "EDGES: dict[tuple[int, int], float] = {"]
    for (a, b) in sorted(edges):
        lines.append(f"    ({a}, {b}): {edges[(a, b)]:.1f},")
    lines += ["}", ""]
    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines))

    by_fac = collections.Counter(v[4] or "-" for v in nodes.values())
    print(f"wrote {os.path.relpath(OUT, ROOT)}: {len(nodes)} nodes "
          f"({by_fac['Alliance']} Alliance, {by_fac['Horde']} Horde, {by_fac['Both']} both, {by_fac['-']} neither), "
          f"{len(edges)} edges")
    if flown:
        print(f"  flown path is {flown / straight:.2f}x the straight line on average "
              f"({flown / 1000:.0f}k yards vs {straight / 1000:.0f}k)")
    if dangling or noline:
        print(f"  skipped {dangling} paths to an excluded node, {noline} with no polyline")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
