-- Lodestar_Guide: Forever overlay — quests, NPCs and positions harvested on the WoW: Forever beta.
-- GENERATED by tools/pfquest/merge_scan.py from LodestarScanDB exports (data/beta/). Do not edit.
-- Merged over Data/Vanilla.lua at load (Data.lua: Guide:MergeForeverData). Coordinates are {0, x, y, m = uiMapID}.
local Guide = _G.Lodestar:GetModule("Guide")
local F = { quests = {}, npcs = {}, objs = {}, taxi = {}, levels = {} }
Guide.ForeverData = F
F.quests[356]={xp={11,650}}
F.quests[369]={xp={11,220}}
F.quests[370]={xp={11,775}}
F.quests[371]={xp={11,850}}
F.quests[374]={xp={11,625}}
F.quests[405]={xp={11,180}}
F.quests[492]={xp={11,875}}
F.quests[7906]={t="Darkmoon Cards - Beasts"}
F.quests[91282]={lvl=11,t="A Second Home"}
F.quests[95314]={lvl=10,o={{n=8,text="Bottle of Whispering Elixir",type="item"}},t="That Shadowvale Green Elixir"}
F.quests[96897]={lvl=13,o={{n=8,text="Dark Neophyte slain",type="monster"},{n=8,text="Dark Enforcer slain",type="monster"}},t="The Cult of the Damned"}
F.quests[96898]={lvl=13,o={{n=12,text="Necrotic Crystal Fragment",type="item"}},t="Remnants of War"}
F.quests[99142]={["end"]={npcs={10665}},lvl=11,o={{n=5,text="Tomb Weed",type="item"}},spots={[1]={{[1]=0,[2]=75,[3]=59.2,m=1420},{[1]=0,[2]=75.4,[3]=59.5,m=1420},{[1]=0,[2]=75.8,[3]=59.9,m=1420},{[1]=0,[2]=76.8,[3]=60.7,m=1420}}},t="Tomb Weed",xp={11,875}}
F.quests[99156]={lvl=13,o={{n=1,text="Riptear's Heart",type="item"}},start={npcs={1495}},t="Rear Guard Patrol",tag="Elite"}
F.npcs[416]={c={{[1]=0,[2]=63.1,[3]=52.2,m=1420}},lvl={8,8},n="Tarpit"}
F.npcs[246152]={c={{[1]=0,[2]=60.2,[3]=53.1,m=1420}},lvl={16,16},n="Shari Stilwell"}
F.levels[10]=7600
F.levels[11]=8800
