-- Lodestar Guides: Alliance 20-25: Ashenvale
--
-- GENERATED by tools/router/generate_route.lua from the merged database (Vanilla + ATT + the
-- beta harvest). Regenerate rather than hand-editing, or the next harvest will overwrite you.
-- --regen-args: 331 --name "Alliance 20-25: Ashenvale" --faction "Alliance" --levels "20-25" --next "Alliance 25-30: Duskwood" --zone "Ashenvale" --max-level "28" --min-level "17"
--
-- 34 quests on uiMapID 331 had a known giver position; 24 carried a prerequisite chain, which is
-- what fixes the order. Quests the data cannot place yet are not in here at all -- smart mode
-- covers those, and they appear as soon as someone walks past their giver.
local Guide = _G.Lodestar:GetModule("Guide")

Guide:RegisterGuide([[
#guide Alliance 20-25: Ashenvale
#faction Alliance
#levels 20-25
#next Alliance 25-30: Duskwood
#author Lodestar (generated)
#note Generated from harvested and ATT data. Order follows the quest chains; positions are where players actually found things.

step
  .goto Ashenvale,36.6,49.6
  .accept 991 >>Accept Raene's Cleansing (lvl 18) from Raene Wolfrunner
  .accept 1054 >>Accept Culling the Threat (lvl 18) from Raene Wolfrunner

step
  .complete 1054 >>Finish Culling the Threat

step
  .goto Ashenvale,20.3,42.3
  .turnin 991 >>Turn in Raene's Cleansing to Teronis' Corpse

step
  .goto Ashenvale,36.6,49.6
  .turnin 1054 >>Turn in Culling the Threat to Raene Wolfrunner

step
  .goto Ashenvale,20.3,42.3
  .accept 1023 >>Accept Raene's Cleansing (lvl 18) from Teronis' Corpse

step
  .goto Ashenvale,36.6,49.6
  .turnin 1023 >>Turn in Raene's Cleansing to Raene Wolfrunner
  .accept 1024 >>Accept Raene's Cleansing (lvl 18) from Raene Wolfrunner
  .accept 1025 >>Accept An Aggressive Defense (lvl 18) from Raene Wolfrunner

step
  .complete 1025 >>Finish An Aggressive Defense

step
  .goto Ashenvale,36.6,49.6
  .turnin 1025 >>Turn in An Aggressive Defense to Raene Wolfrunner

step
  .goto Ashenvale,53.5,46.2
  .turnin 1024 >>Turn in Raene's Cleansing to Shael'dryn
  .accept 1029 >>Accept Raene's Cleansing (lvl 18) from Shael'dryn
  .accept 1026 >>Accept Raene's Cleansing (lvl 18) from Shael'dryn

step
  .complete 1026 >>Finish Raene's Cleansing

step
  .goto Ashenvale,36.6,49.6
  .turnin 1029 >>Turn in Raene's Cleansing to Raene Wolfrunner

step
  .goto Ashenvale,53.5,46.2
  .turnin 1026 >>Turn in Raene's Cleansing to Shael'dryn

step
  .xp 21

step
  .goto Ashenvale,36.6,49.6
  .accept 1030 >>Accept Raene's Cleansing (lvl 18) from Raene Wolfrunner

step
  .goto Ashenvale,50.8,75.1
  .turnin 1030 >>Turn in Raene's Cleansing to Krolg
  .accept 1045 >>Accept Raene's Cleansing (lvl 18) from Krolg

step
  .complete 1045 >>Finish Raene's Cleansing

step
  .goto Ashenvale,50.8,75.1
  .turnin 1045 >>Turn in Raene's Cleansing to Krolg
  .accept 1046 >>Accept Raene's Cleansing (lvl 18) from Krolg

step
  .goto Ashenvale,36.6,49.6
  .turnin 1046 >>Turn in Raene's Cleansing to Raene Wolfrunner

step
  .goto Ashenvale,35.8,49.1
  .accept 1056 >>Accept Journey to Stonetalon Peak (lvl 18) from Faldreas Goeth'Shael

step
  .optional >>Handed in outside this zone, to Keeper Albagorm
  .turnin 1056 >>Turn in Journey to Stonetalon Peak to Keeper Albagorm (not in this zone)

step
  .goto Ashenvale,34.9,49.8
  .accept 1081 >>Accept Reception from Tyrande (lvl 17) from Sentinel Thenysil
  .accept 1070 >>Accept On Guard in Stonetalon (lvl 17) from Sentinel Thenysil

step
  .optional >>Handed in outside this zone, to Tyrande Whisperwind
  .turnin 1081 >>Turn in Reception from Tyrande to Tyrande Whisperwind (not in this zone)

step
  .optional >>Handed in outside this zone, to Kaela Shadowspear
  .turnin 1070 >>Turn in On Guard in Stonetalon to Kaela Shadowspear (not in this zone)

step
  .goto Ashenvale,34.7,48.8
  .accept 1134 >>Accept Pridewings of Stonetalon (lvl 18) from Shindrell Swiftfire

step
  .complete 1134 >>Finish Pridewings of Stonetalon

step
  .goto Ashenvale,34.7,48.8
  .turnin 1134 >>Turn in Pridewings of Stonetalon to Shindrell Swiftfire

step
  .xp 22

step
  .goto Ashenvale,26.4,38.6
  .accept 1010 >>Accept Bathran's Hair (lvl 20) from Orendil Broadleaf

step
  .complete 1010 >>Finish Bathran's Hair

step
  .goto Ashenvale,26.4,38.6
  .turnin 1010 >>Turn in Bathran's Hair to Orendil Broadleaf
  .accept 1020 >>Accept Orendil's Cure (lvl 20) from Orendil Broadleaf

step
  .goto Ashenvale,37.4,51.8
  .turnin 1020 >>Turn in Orendil's Cure to Pelturas Whitemoon
  .accept 1033 >>Accept Elune's Tear (lvl 20) from Pelturas Whitemoon

step
  .complete 1033 >>Finish Elune's Tear

step
  .goto Ashenvale,37.4,51.8
  .turnin 1033 >>Turn in Elune's Tear to Pelturas Whitemoon
  .accept 1034 >>Accept The Ruins of Stardust (lvl 20) from Pelturas Whitemoon

step
  .complete 1034 >>Finish The Ruins of Stardust

step
  .goto Ashenvale,37.4,51.8
  .turnin 1034 >>Turn in The Ruins of Stardust to Pelturas Whitemoon
  .accept 1035 >>Accept Fallen Sky Lake (lvl 20) from Pelturas Whitemoon

step
  .complete 1035 >>Finish Fallen Sky Lake

step
  .goto Ashenvale,37.4,51.8
  .turnin 1035 >>Turn in Fallen Sky Lake to Pelturas Whitemoon

step
  .goto Ashenvale,53.5,46.2
  .accept 1027 >>Accept Raene's Cleansing (lvl 18) from Shael'dryn

step
  .complete 1027 >>Finish Raene's Cleansing

step
  .goto Ashenvale,53.5,46.2
  .turnin 1027 >>Turn in Raene's Cleansing to Shael'dryn
  .accept 1028 >>Accept Raene's Cleansing (lvl 18) from Shael'dryn

step
  .goto Ashenvale,56.4,49.2
  .turnin 1028 >>Turn in Raene's Cleansing

step
  .xp 23

step
  .goto Ashenvale,49.8,67.2
  .accept 1016 >>Accept Elemental Bracers (lvl 20) from Sentinel Velene Starstrike

step
  .complete 1016 >>Finish Elemental Bracers

step
  .goto Ashenvale,49.8,67.2
  .turnin 1016 >>Turn in Elemental Bracers to Sentinel Velene Starstrike
  .accept 1017 >>Accept Mage Summoner (lvl 20) from Sentinel Velene Starstrike

step
  .complete 1017 >>Finish Mage Summoner

step
  .goto Ashenvale,49.8,67.2
  .turnin 1017 >>Turn in Mage Summoner to Sentinel Velene Starstrike

step
  .goto Ashenvale,61.9,83.8
  .accept 8372 >>Accept Fight for Warsong Gulch (lvl 19) from Alliance Brigadier General

step
  .complete 8372 >>Finish Fight for Warsong Gulch

step
  .goto Ashenvale,61.9,83.8
  .turnin 8372 >>Turn in Fight for Warsong Gulch to Alliance Brigadier General
  .accept 8386 >>Accept Fight for Warsong Gulch (lvl 19) from Alliance Brigadier General

step
  .complete 8386 >>Finish Fight for Warsong Gulch

step
  .goto Ashenvale,61.9,83.8
  .turnin 8386 >>Turn in Fight for Warsong Gulch to Alliance Brigadier General
  .accept 7921 >>Accept Talismans of Merit (lvl 25) from Alliance Brigadier General

step
  .complete 7921 >>Finish Talismans of Merit

step
  .goto Ashenvale,61.9,83.9
  .turnin 7921 >>Turn in Talismans of Merit to Sentinel Farsong

step
  .goto Ashenvale,26.2,38.9
  .accept 976 >>Accept Supplies to Auberdine (lvl 19) from Feero Ironhand

step
  .goto Ashenvale,26.2,38.7
  .turnin 976 >>Turn in Supplies to Auberdine to Delgren the Purifier

step
  .goto Ashenvale,14.8,31.3
  .accept 1007 >>Accept The Ancient Statuette (lvl 19) from Talen

step
  .complete 1007 >>Finish The Ancient Statuette

step
  .goto Ashenvale,14.8,31.3
  .turnin 1007 >>Turn in The Ancient Statuette to Talen

step
  .xp 24

step
  .goto Ashenvale,14.8,31.3
  .accept 1009 >>Accept Ruuzel (lvl 20) from Talen

step
  .complete 1009 >>Finish Ruuzel

step
  .goto Ashenvale,14.8,31.3
  .turnin 1009 >>Turn in Ruuzel to Talen

step
  .goto Ashenvale,34.7,48.8
  .accept 4581 >>Accept Kayneth Stillwind (lvl 24) from Shindrell Swiftfire

step
  .goto Ashenvale,85.3,44.7
  .turnin 4581 >>Turn in Kayneth Stillwind to Kayneth Stillwind
  .accept 1011 >>Accept Forsaken Diseases (lvl 24) from Kayneth Stillwind

step
  .complete 1011 >>Finish Forsaken Diseases

step
  .goto Ashenvale,85.3,44.7
  .turnin 1011 >>Turn in Forsaken Diseases to Kayneth Stillwind
  .accept 1012 >>Accept Insane Druids (lvl 24) from Kayneth Stillwind

step
  .complete 1012 >>Finish Insane Druids

step
  .goto Ashenvale,85.3,44.7
  .turnin 1012 >>Turn in Insane Druids to Kayneth Stillwind

step
  .xp 25 >>You should be 25 by now. If you are not, the rest of this zone will not be offered to you yet -- finish the optional quests above, or kill your way up, before carrying on.

step
  .goto Ashenvale,22.2,53.0
  .accept 1022 >>Accept The Howling Vale (lvl 25) from Sentinel Melyria Frostshadow

step
  .complete 1022 >>Finish The Howling Vale

step
  .goto Ashenvale,22.2,53.0
  .turnin 1022 >>Turn in The Howling Vale to Sentinel Melyria Frostshadow
  .accept 1037 >>Accept Velinde Starsong (lvl 25) from Sentinel Melyria Frostshadow

step
  .optional >>Handed in outside this zone, to Thyn'tel Bladeweaver
  .turnin 1037 >>Turn in Velinde Starsong to Thyn'tel Bladeweaver (not in this zone)

]], "generated")
