-- Lodestar Guides: Alliance 20-25: Redridge Mountains
--
-- GENERATED by tools/router/generate_route.lua from the merged database (Vanilla + ATT + the
-- beta harvest). Regenerate rather than hand-editing, or the next harvest will overwrite you.
-- --regen-args: 44 --name "Alliance 20-25: Redridge Mountains" --faction "Alliance" --levels "20-25" --next "Alliance 25-30: Duskwood" --zone "Redridge Mountains" --max-level "26" --min-level "14"
--
-- 26 quests on uiMapID 44 had a known giver position; 14 carried a prerequisite chain, which is
-- what fixes the order. Quests the data cannot place yet are not in here at all -- smart mode
-- covers those, and they appear as soon as someone walks past their giver.
local Guide = _G.Lodestar:GetModule("Guide")

Guide:RegisterGuide([[
#guide Alliance 20-25: Redridge Mountains
#faction Alliance
#levels 20-25
#next Alliance 25-30: Duskwood
#author Lodestar (generated)
#note Generated from harvested and ATT data. Order follows the quest chains; positions are where players actually found things.

step
  .goto Redridge Mountains,31.0,47.3
  .accept 118 >>Accept The Price of Shoes (lvl 14) from Verner Osgood

step
  .optional >>Handed in outside this zone, to Smith Argus
  .turnin 118 >>Turn in The Price of Shoes to Smith Argus (not in this zone)

step
  .goto Redridge Mountains,31.0,47.3
  .accept 122 >>Accept Underbelly Scales (lvl 14) from Verner Osgood
  .accept 124 >>Accept A Baying of Gnolls (lvl 15) from Verner Osgood

step
  .complete 122 >>Finish Underbelly Scales

step
  .complete 124 >>Finish A Baying of Gnolls

step
  .goto Redridge Mountains,31.0,47.3
  .turnin 122 >>Turn in Underbelly Scales to Verner Osgood
  .turnin 124 >>Turn in A Baying of Gnolls to Verner Osgood

step
  .goto Redridge Mountains,32.1,48.6
  .accept 125 >>Accept The Lost Tools (lvl 15) from Foreman Oslow
  .accept 347 >>Accept Rethban Ore (lvl 20) from Foreman Oslow

step
  .complete 125 >>Finish The Lost Tools

step
  .goto Redridge Mountains,32.1,48.6
  .turnin 125 >>Turn in The Lost Tools to Foreman Oslow

step
  .optional >>Handed in outside this zone, to Brother Paxton
  .turnin 347 >>Turn in Rethban Ore to Brother Paxton (not in this zone)

step
  .goto Redridge Mountains,33.5,49.0
  .accept 20 >>Accept Blackrock Menace (lvl 18) from Marshal Marris

step
  .complete 20 >>Finish Blackrock Menace

step
  .goto Redridge Mountains,33.5,49.0
  .turnin 20 >>Turn in Blackrock Menace to Marshal Marris

step
  .xp 21

step
  .goto Redridge Mountains,33.5,49.0
  .accept 115 >>Accept Shadow Magic (lvl 18) from Marshal Marris
  .accept 19 >>Accept Tharil'zun (lvl 18) from Marshal Marris

step
  .complete 115 >>Finish Shadow Magic

step
  .complete 19 >>Finish Tharil'zun

step
  .goto Redridge Mountains,33.5,49.0
  .turnin 115 >>Turn in Shadow Magic to Marshal Marris
  .turnin 19 >>Turn in Tharil'zun to Marshal Marris

step
  .goto Redridge Mountains,32.1,48.6
  .accept 89 >>Accept The Everstill Bridge (lvl 15) from Foreman Oslow

step
  .complete 89 >>Finish The Everstill Bridge

step
  .goto Redridge Mountains,32.1,48.6
  .turnin 89 >>Turn in The Everstill Bridge to Foreman Oslow

step
  .goto Redridge Mountains,28.1,52.0
  .accept 2282 >>Accept Alther's Mill (lvl 16) from Lucius

step
  .complete 2282 >>Finish Alther's Mill

step
  .goto Redridge Mountains,28.1,52.0
  .turnin 2282 >>Turn in Alther's Mill to Lucius
  .accept 2358 >>Accept Horns of Nez'ra (lvl 16) from Lucius

step
  .complete 2358 >>Finish Horns of Nez'ra

step
  .goto Redridge Mountains,28.1,52.3
  .turnin 2358 >>Turn in Horns of Nez'ra to Arantir

step
  .xp 22

step
  .goto Redridge Mountains,26.6,44.7
  .accept 1699 >>Accept The Rethban Gauntlet (lvl 20) from Yorus Barleybrew

step
  .complete 1699 >>Finish The Rethban Gauntlet

step
  .goto Redridge Mountains,26.6,44.7
  .turnin 1699 >>Turn in The Rethban Gauntlet to Yorus Barleybrew
  .accept 1702 >>Accept The Shieldsmith (lvl 20) from Yorus Barleybrew

step
  .optional >>Handed in outside this zone, to Furen Longbeard
  .turnin 1702 >>Turn in The Shieldsmith to Furen Longbeard (not in this zone)

step
  .goto Redridge Mountains,26.5,45.3
  .accept 132 >>Accept The Defias Brotherhood (lvl 14) from Wiley the Black

step
  .optional >>Handed in outside this zone, to Gryan Stoutmantle
  .turnin 132 >>Turn in The Defias Brotherhood to Gryan Stoutmantle (not in this zone)

step
  .goto Redridge Mountains,26.3,46.6
  .accept 386 >>Accept What Comes Around... (lvl 22) from Guard Berton

step
  .complete 386 >>Finish What Comes Around...

step
  .goto Redridge Mountains,26.3,46.6
  .turnin 386 >>Turn in What Comes Around... to Guard Berton

step
  .goto Redridge Mountains,27.7,47.4
  .accept 127 >>Accept Selling Fish (lvl 16) from Dockmaster Baren
  .accept 150 >>Accept Murloc Poachers (lvl 20) from Dockmaster Baren

step
  .complete 127 >>Finish Selling Fish

step
  .complete 150 >>Finish Murloc Poachers

step
  .goto Redridge Mountains,27.7,47.4
  .turnin 127 >>Turn in Selling Fish to Dockmaster Baren
  .turnin 150 >>Turn in Murloc Poachers to Dockmaster Baren

step
  .xp 23

step
  .goto Redridge Mountains,31.0,47.3
  .accept 126 >>Accept Howling in the Hills (lvl 15) from Verner Osgood

step
  .complete 126 >>Finish Howling in the Hills

step
  .goto Redridge Mountains,31.0,47.3
  .turnin 126 >>Turn in Howling in the Hills to Verner Osgood

step
  .goto Redridge Mountains,30.0,44.5
  .accept 120 >>Accept Messenger to Stormwind (lvl 14) from Magistrate Solomon
  .accept 143 >>Accept Messenger to Westfall (lvl 14) from Magistrate Solomon
  .accept 145 >>Accept Messenger to Darkshire (lvl 18) from Magistrate Solomon

step
  .optional >>Handed in outside this zone, to General Marcus Jonathan
  .turnin 120 >>Turn in Messenger to Stormwind to General Marcus Jonathan (not in this zone)

step
  .optional >>Handed in outside this zone, to Gryan Stoutmantle
  .turnin 143 >>Turn in Messenger to Westfall to Gryan Stoutmantle (not in this zone)

step
  .optional >>Handed in outside this zone, to Lord Ello Ebonlocke
  .turnin 145 >>Turn in Messenger to Darkshire to Lord Ello Ebonlocke (not in this zone)

step
  .xp 24

step
  .goto Redridge Mountains,29.7,44.3
  .accept 91 >>Accept Solomon's Law (lvl 17) from Bailiff Conacher

step
  .complete 91 >>Finish Solomon's Law

step
  .goto Redridge Mountains,29.7,44.3
  .turnin 91 >>Turn in Solomon's Law to Bailiff Conacher

step
  .goto Redridge Mountains,22.7,43.8
  .accept 92 >>Accept Redridge Goulash (lvl 15) from Chef Breanna

step
  .complete 92 >>Finish Redridge Goulash

step
  .goto Redridge Mountains,22.7,43.8
  .turnin 92 >>Turn in Redridge Goulash to Chef Breanna

step
  .goto Redridge Mountains,21.9,46.3
  .accept 34 >>Accept An Unwelcome Guest (lvl 18) from Martie Jainrose

step
  .complete 34 >>Finish An Unwelcome Guest

step
  .goto Redridge Mountains,21.9,46.3
  .turnin 34 >>Turn in An Unwelcome Guest to Martie Jainrose

step
  .goto Redridge Mountains,31.5,57.9
  .accept 128 >>Accept Blackrock Bounty (lvl 20) from Guard Howe

step
  .complete 128 >>Finish Blackrock Bounty

step
  .goto Redridge Mountains,31.5,57.9
  .turnin 128 >>Turn in Blackrock Bounty to Guard Howe

step
  .goto Redridge Mountains,28.4,12.6
  .accept 219 >>Accept Missing In Action (lvl 19) from Corporal Keeshan

step
  .goto Redridge Mountains,33.5,49.0
  .turnin 219 >>Turn in Missing In Action to Marshal Marris

step
  .xp 25

]], "generated")
