-- Lodestar Guides: Alliance 20-25: Wetlands
--
-- GENERATED by tools/router/generate_route.lua from the merged database (Vanilla + ATT + the
-- beta harvest). Regenerate rather than hand-editing, or the next harvest will overwrite you.
-- --regen-args: 11 --name "Alliance 20-25: Wetlands" --faction "Alliance" --levels "20-25" --next "Alliance 25-30: Duskwood" --zone "Wetlands" --max-level "27" --min-level "14"
--
-- 32 quests on uiMapID 11 had a known giver position; 20 carried a prerequisite chain, which is
-- what fixes the order. Quests the data cannot place yet are not in here at all -- smart mode
-- covers those, and they appear as soon as someone walks past their giver.
local Guide = _G.Lodestar:GetModule("Guide")

Guide:RegisterGuide([[
#guide Alliance 20-25: Wetlands
#faction Alliance
#levels 20-25
#next Alliance 25-30: Duskwood
#author Lodestar (generated)
#note Generated from harvested and ATT data. Order follows the quest chains; positions are where players actually found things.

step
  .goto Wetlands,8.5,55.7
  .accept 484 >>Accept Young Crocolisk Skins (lvl 18) from James Halloran

step
  .complete 484 >>Finish Young Crocolisk Skins

step
  .goto Wetlands,8.5,55.7
  .turnin 484 >>Turn in Young Crocolisk Skins to James Halloran

step
  .goto Wetlands,8.3,58.6
  .accept 279 >>Accept Claws from the Deep (lvl 20) from Karl Boran

step
  .complete 279 >>Finish Claws from the Deep

step
  .goto Wetlands,8.3,58.6
  .turnin 279 >>Turn in Claws from the Deep to Karl Boran

step
  .goto Wetlands,10.9,59.6
  .accept 463 >>Accept The Greenwarden (lvl 20) from First Mate Fitzsimmons

step
  .goto Wetlands,56.4,40.4
  .turnin 463 >>Turn in The Greenwarden to Rethiel the Greenwarden
  .accept 276 >>Accept Tramping Paws (lvl 20) from Rethiel the Greenwarden

step
  .complete 276 >>Finish Tramping Paws

step
  .goto Wetlands,56.4,40.4
  .turnin 276 >>Turn in Tramping Paws to Rethiel the Greenwarden
  .accept 277 >>Accept Fire Taboo (lvl 20) from Rethiel the Greenwarden

step
  .complete 277 >>Finish Fire Taboo

step
  .goto Wetlands,56.4,40.4
  .turnin 277 >>Turn in Fire Taboo to Rethiel the Greenwarden
  .accept 275 >>Accept Blisters on The Land (lvl 20) from Rethiel the Greenwarden

step
  .complete 275 >>Finish Blisters on The Land

step
  .goto Wetlands,56.4,40.4
  .turnin 275 >>Turn in Blisters on The Land to Rethiel the Greenwarden

step
  .goto Wetlands,49.9,39.4
  .accept 469 >>Accept Daily Delivery (lvl 18) from Einar Stonegrip

step
  .goto Wetlands,8.5,55.7
  .turnin 469 >>Turn in Daily Delivery to James Halloran

step
  .xp 21

step
  .goto Wetlands,8.5,55.7
  .accept 471 >>Accept Apprentice's Duties (lvl 18) from James Halloran

step
  .complete 471 >>Finish Apprentice's Duties

step
  .goto Wetlands,8.5,55.7
  .turnin 471 >>Turn in Apprentice's Duties to James Halloran

step
  .goto Wetlands,11.5,52.2
  .accept 305 >>Accept In Search of The Excavation Team (lvl 21) from Tarrel Rockweaver

step
  .goto Wetlands,38.9,52.3
  .turnin 305 >>Turn in In Search of The Excavation Team to Merrin Rockweaver
  .accept 306 >>Accept In Search of The Excavation Team (lvl 21) from Merrin Rockweaver

step
  .goto Wetlands,11.5,52.2
  .turnin 306 >>Turn in In Search of The Excavation Team to Tarrel Rockweaver

step
  .goto Wetlands,10.6,60.6
  .accept 321 >>Accept Lightforge Iron (lvl 20) from Glorin Steelbrow

step
  .goto Wetlands,12.1,64.2
  .turnin 321 >>Turn in Lightforge Iron

step
  .goto Wetlands,10.6,60.6
  .accept 526 >>Accept Lightforge Ingots (lvl 20) from Glorin Steelbrow

step
  .complete 526 >>Finish Lightforge Ingots

step
  .goto Wetlands,10.6,60.6
  .turnin 526 >>Turn in Lightforge Ingots to Glorin Steelbrow
  .accept 322 >>Accept Blessed Arm (lvl 20) from Glorin Steelbrow

step
  .optional >>Handed in outside this zone, to Grimand Elmore
  .turnin 322 >>Turn in Blessed Arm to Grimand Elmore (not in this zone)

step
  .xp 22

step
  .goto Wetlands,10.9,59.6
  .accept 288 >>Accept The Third Fleet (lvl 22) from First Mate Fitzsimmons

step
  .complete 288 >>Finish The Third Fleet

step
  .goto Wetlands,10.9,59.6
  .turnin 288 >>Turn in The Third Fleet to First Mate Fitzsimmons
  .accept 289 >>Accept The Cursed Crew (lvl 22) from First Mate Fitzsimmons

step
  .complete 289 >>Finish The Cursed Crew

step
  .goto Wetlands,10.9,59.6
  .turnin 289 >>Turn in The Cursed Crew to First Mate Fitzsimmons
  .accept 290 >>Accept Lifting the Curse (lvl 22) from First Mate Fitzsimmons

step
  .goto Wetlands,14.4,24.0
  .turnin 290 >>Turn in Lifting the Curse

step
  .goto Wetlands,38.2,50.9
  .accept 294 >>Accept Ormer's Revenge (lvl 22) from Ormer Ironbraid

step
  .complete 294 >>Finish Ormer's Revenge

step
  .goto Wetlands,38.2,50.9
  .turnin 294 >>Turn in Ormer's Revenge to Ormer Ironbraid
  .accept 295 >>Accept Ormer's Revenge (lvl 22) from Ormer Ironbraid

step
  .complete 295 >>Finish Ormer's Revenge

step
  .goto Wetlands,38.2,50.9
  .turnin 295 >>Turn in Ormer's Revenge to Ormer Ironbraid
  .accept 296 >>Accept Ormer's Revenge (lvl 22) from Ormer Ironbraid

step
  .complete 296 >>Finish Ormer's Revenge

step
  .goto Wetlands,38.2,50.9
  .turnin 296 >>Turn in Ormer's Revenge to Ormer Ironbraid

step
  .goto Wetlands,11.8,58.0
  .accept 470 >>Accept Digging Through the Ooze (lvl 19) from Sida

step
  .complete 470 >>Finish Digging Through the Ooze

step
  .goto Wetlands,11.8,58.0
  .turnin 470 >>Turn in Digging Through the Ooze to Sida

step
  .xp 23

step
  .goto Wetlands,10.1,56.9
  .accept 473 >>Accept Report to Captain Stoutfist (lvl 23) from Valstag Ironjaw

step
  .goto Wetlands,9.9,57.5
  .turnin 473 >>Turn in Report to Captain Stoutfist to Captain Stoutfist
  .accept 464 >>Accept War Banners (lvl 23) from Captain Stoutfist

step
  .complete 464 >>Finish War Banners

step
  .goto Wetlands,9.9,57.5
  .turnin 464 >>Turn in War Banners to Captain Stoutfist
  .accept 465 >>Accept Nek'rosh's Gambit (lvl 23) from Captain Stoutfist

step
  .goto Wetlands,47.5,47.0
  .turnin 465 >>Turn in Nek'rosh's Gambit

step
  .goto Wetlands,50.0,18.2
  .accept 274 >>Accept A Dark Threat Looms (lvl 16) from Ashlan Stonesmirk

step
  .optional >>Handed in outside this zone, to Chief Engineer Hinderweir VII
  .turnin 274 >>Turn in A Dark Threat Looms to Chief Engineer Hinderweir VII (not in this zone)

step
  .goto Wetlands,10.0,58.0
  .accept 1132 >>Accept Fiora Longears (lvl 18) from Red Jack Flint

step
  .optional >>Handed in outside this zone, to Fiora Longears
  .turnin 1132 >>Turn in Fiora Longears to Fiora Longears (not in this zone)

step
  .goto Wetlands,8.3,58.6
  .accept 281 >>Accept Reclaiming Goods (lvl 20) from Karl Boran

step
  .goto Wetlands,13.5,41.4
  .turnin 281 >>Turn in Reclaiming Goods

step
  .xp 24

step
  .goto Wetlands,10.8,60.4
  .accept 943 >>Accept The Absent Minded Prospector (lvl 15) from Archaeologist Flagongut

step
  .complete 943 >>Finish The Absent Minded Prospector

step
  .goto Wetlands,10.8,60.4
  .turnin 943 >>Turn in The Absent Minded Prospector to Archaeologist Flagongut
  .accept 293 >>Accept Cleansing the Eye (lvl 22) from Archaeologist Flagongut

step
  .optional >>Handed in outside this zone, to Archbishop Benedictus
  .turnin 293 >>Turn in Cleansing the Eye to Archbishop Benedictus (not in this zone)

step
  .xp 25 >>You should be 25 by now. If you are not, the rest of this zone will not be offered to you yet -- finish the optional quests above, or kill your way up, before carrying on.

step
  .goto Wetlands,10.8,55.9
  .accept 472 >>Accept Fall of Dun Modr (lvl 25) from Harlo Barnaby

step
  .goto Wetlands,49.8,18.3
  .turnin 472 >>Turn in Fall of Dun Modr to Longbraid the Grim
  .accept 303 >>Accept The Dark Iron War (lvl 25) from Longbraid the Grim

step
  .complete 303 >>Finish The Dark Iron War

step
  .goto Wetlands,49.7,18.2
  .turnin 303 >>Turn in The Dark Iron War to Motley Garmason
  .accept 378 >>Accept The Fury Runs Deep (lvl 25) from Motley Garmason

step
  .complete 378 >>Finish The Fury Runs Deep

step
  .goto Wetlands,49.7,18.2
  .turnin 378 >>Turn in The Fury Runs Deep to Motley Garmason

step
  .goto Wetlands,38.8,52.4
  .accept 299 >>Accept Uncovering the Past (lvl 25) from Prospector Whelgar

step
  .complete 299 >>Finish Uncovering the Past

step
  .goto Wetlands,38.8,52.4
  .turnin 299 >>Turn in Uncovering the Past to Prospector Whelgar

]], "generated")
