#!/usr/bin/env bash
# Fold a play session's harvest back into the shipped database, and rebuild what depends on it.
#
#   tools/refresh_harvest.sh <path to SavedVariables/Lodestar_Guide.lua> [more.lua ...]
#
# This is the loop that makes the suite better the more anyone plays. A session records NPC
# positions, quest givers and enders, objective spots, flight points and XP; the client writes that
# to disk at logout; this turns it into JSON, merges it with every earlier export into
# Data/Forever.lua, and regenerates the routes that were derived from it.
#
# Exports accumulate in data/beta/ on purpose. The merge is over ALL of them, not just the newest,
# so a position someone recorded in August still counts in September and no single bad session can
# quietly delete what everyone else contributed.
#
# On the beta the client does not appear to hand saved variables back at login, which makes this the
# only way a harvest survives at all -- the file is still written, it just never comes back. Run it
# after a session and the data is safe in the repo rather than in one player's WTF folder.
set -euo pipefail
cd "$(dirname "$0")/.."

if [ $# -lt 1 ]; then
  echo "usage: tools/refresh_harvest.sh <SavedVariables/Lodestar_Guide.lua> [more.lua ...]" >&2
  exit 2
fi

mkdir -p data/beta
stamp="$(date -u +%Y-%m-%dT%H%M%SZ)"
n=0
for src in "$@"; do
  if [ ! -f "$src" ]; then
    echo "refresh_harvest: no such file: $src" >&2
    exit 1
  fi
  n=$((n + 1))
  out="data/beta/scan-${stamp}-${n}.json"
  lua5.1 tools/pfquest/sv_to_json.lua "$src" > "$out"
  # An export with no quests is a session that harvested nothing, or a saved-variable file the
  # client handed back empty. Keeping it would add a dated file that says nothing.
  if ! grep -q '"quests"' "$out"; then
    echo "refresh_harvest: $src carried no quests; dropping $out"
    rm -f "$out"
    n=$((n - 1))
    continue
  fi
  echo "refresh_harvest: $src -> $out ($(wc -c < "$out") bytes)"
done

if [ "$n" -eq 0 ]; then
  echo "refresh_harvest: nothing new to merge" >&2
  exit 1
fi

echo "--- merging $(ls data/beta/*.json | wc -l) export(s) into Data/Forever.lua ---"
python3 tools/pfquest/merge_scan.py data/beta/*.json

# Regenerate every route that was derived rather than hand-authored. A hand-written guide is left
# alone: the marker is the generator's own header line, so this can never overwrite someone's work.
echo "--- regenerating derived routes ---"
for guide in Lodestar_Guides_*/*.lua; do
  if head -5 "$guide" | grep -q "GENERATED by tools/router/generate_route.lua"; then
    args="$(grep -m1 -- "--regen-args:" "$guide" | sed 's/.*--regen-args: //')"
    if [ -z "$args" ]; then
      echo "  $guide: no --regen-args line, leaving it alone"
      continue
    fi
    tmp="$(mktemp)"
    # shellcheck disable=SC2086
    if lua5.1 tools/router/generate_route.lua $args > "$tmp"; then
      if cmp -s "$tmp" "$guide"; then
        echo "  $guide: unchanged"
      else
        mv "$tmp" "$guide"
        echo "  $guide: rebuilt"
      fi
    fi
    rm -f "$tmp"
  fi
done

echo "--- verifying ---"
python3 tools/router/lint_guides.py
lua5.1 tools/smoke/run.lua
echo "refresh_harvest: done. Review the diff before committing."
