"""CLI.

  python -m tools.router plan examples/deathknell.json --target 6 [--class Warlock] [--lap recording.json] [-o out.txt]
  python -m tools.router /tmp/durotar.json                                         # "plan" is the default subcommand
  python -m tools.router score examples/deathknell.json --lap recording.json      # replay a human lap under the model
  python -m tools.router xp-table 1 12                                            # sanity: XP to level
"""
from __future__ import annotations

import argparse
import sys

from . import xp as XP
from .catalog import load
from .cost import CostModel
from .emit import GuideHeader, emit
from .laps import calibrate, load_entries, steps_from_lap
from .router import Planner, PlannerConfig, plan_two_pass
from .validate import replay


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="tools.router")
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("plan")
    p.add_argument("catalog")
    p.add_argument("--target", type=int, default=None, help="level to plan to (default: the catalog's level band, else 6)")
    p.add_argument("--class", dest="player_class", default=None)
    p.add_argument("--lap", action="append", default=[], help="recording.json from sv2json.lua; repeatable")
    p.add_argument("--name", default=None)
    p.add_argument("--next", dest="next_guide", default=None)
    p.add_argument("-o", "--out", default=None)
    p.add_argument("--no-comments", action="store_true")
    s = sub.add_parser("score")
    s.add_argument("catalog")
    s.add_argument("--lap", required=True)
    x = sub.add_parser("xp-table")
    x.add_argument("lo", type=int)
    x.add_argument("hi", type=int)
    argv = list(sys.argv[1:] if argv is None else argv)
    if argv and argv[0] not in ("plan", "score", "xp-table", "-h", "--help"):
        argv.insert(0, "plan")
    args = ap.parse_args(argv)

    if args.cmd == "xp-table":
        for l in range(args.lo, args.hi + 1):
            print(l, XP.xp_to_level(l), XP.total_xp_at(l + 1))
        return 0

    cat, world, start, raw = load(args.catalog)
    cm = CostModel()
    if args.cmd == "score":
        entries = load_entries(args.lap)
        calibrate(entries, cat, world, cm)
        steps = steps_from_lap(entries, cat, world=world)
        rep = replay(steps, cat, world, cm, start)
        print(f"human lap: {rep.total_seconds/60:.1f} min to level {rep.final_level}, {rep.xp_per_minute:.0f} xp/min")
        for i in rep.issues:
            print("  issue:", i)
        return 0

    for lap in args.lap:
        stats = calibrate(load_entries(lap), cat, world, cm)
        print(f"calibrated from {lap}: {stats['npc_updates']} npc fixes, {stats['legs']} legs, "
              f"{len(stats['ttk_samples'])} kill samples, class_factor={cm.class_factor:.2f}", file=sys.stderr)
    if args.player_class:
        start.player_class = args.player_class
    target = args.target or (raw.get("levels") or [0, 6])[1]
    cfg = PlannerConfig(target_level=target)
    steps, planner = plan_two_pass(cat, world, cm, cfg, start)
    rep = replay(steps, cat, world, cm, start)   # recompute times after pruning/merging, check invariants
    for issue in rep.issues:
        print("VALIDATION:", issue, file=sys.stderr)
    for note in rep.notes:
        print("note:", note, file=sys.stderr)
    zone = raw.get("zone") or planner.hubs[0].name
    name = args.name or f"{cat.faction}/{cat.race} {start.level}-{rep.final_level}: {zone} (router)"
    header = GuideHeader(name=name, faction=cat.faction, races=[cat.race] if cat.race else [],
                         classes=[start.player_class] if start.player_class else [],
                         levels=(start.level, rep.final_level), next=args.next_guide,
                         note=f"Generated by tools/router: {rep.total_seconds/60:.0f} min simulated, {rep.xp_per_minute:.0f} xp/min. Verify with /lode record.")
    text = emit(header, steps, cat, with_sim_comments=not args.no_comments)
    if args.out:
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(text)
        print(f"wrote {args.out}: {len(steps)} steps, {rep.total_seconds/60:.1f} min simulated to level {rep.final_level}", file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 1 if rep.issues else 0


if __name__ == "__main__":
    raise SystemExit(main())
