#!/usr/bin/env bash
# Rebuild every generated route from the databases, using each file's own --regen-args line.
#
#   tools/router/regen.sh [name-fragment]
#
# A generated guide records the exact command that produced it in its header. That is the only
# record: there is no separate manifest to drift out of step with the files, and a hand-written
# guide has no such line and is never touched. Pass a fragment to rebuild a subset while iterating.
#
# refresh_harvest.sh does this as its last step after merging a new harvest; this is the same
# regeneration on its own, for when the generator changed rather than the data.
set -euo pipefail
cd "$(dirname "$0")/../.."
only="${1:-}"
built=0 changed=0
for guide in Lodestar_Guides_*/*.lua; do
  head -5 "$guide" | grep -q "GENERATED by tools/router/generate_route.lua" || continue
  [ -n "$only" ] && [[ "$guide" != *"$only"* ]] && continue
  args="$(grep -m1 -- "--regen-args:" "$guide" | sed 's/.*--regen-args: //')"
  if [ -z "$args" ]; then
    echo "  $guide: no --regen-args line, leaving it alone" >&2
    continue
  fi
  tmp="$(mktemp)"
  # shellcheck disable=SC2086
  if eval "lua5.1 tools/router/generate_route.lua $args" > "$tmp" 2>/dev/null; then
    built=$((built + 1))
    if cmp -s "$tmp" "$guide"; then
      echo "  $(basename "$guide"): unchanged"
    else
      mv "$tmp" "$guide"
      changed=$((changed + 1))
      echo "  $(basename "$guide"): rebuilt ($(grep -c '^step' "$guide") steps)"
    fi
  else
    echo "  $(basename "$guide"): FAILED to generate" >&2
  fi
  rm -f "$tmp"
done
echo "regen: $built route(s) built, $changed changed"
